### PR TITLE
Feature pack

### PR DESCRIPTION
**Pull request by bobmcwhirter**
Add descriptors for wildfly-feature-pack.xml (also encompasses previous PR for deprecations, apparently, because I suck).

### CODE REVIEW

**Comment by ALRubinger** [comment]
Sent to @ralfbattenfeld for review.

**Comment by rbattenfeld** [comment]
Absolutely fine. Thanks Bob, for cleaning up the assert imports.

**Comment by bobmcwhirter** [comment]
Apologies for the meaningless whitespace changes in the diff!

**Comment by ALRubinger** [comment]
08fad0255b2031d70708c716df353060969157a1

**Comment by ALRubinger** [comment]
https://issues.jboss.org/browse/SHRINKDESC-167

**Pull request closed without merging**
